import { useState } from "react";
import { useQuery, useMutation, useAction } from "convex/react";
import { api } from "@/convex/_generated/api.js";
import { Authenticated, Unauthenticated } from "convex/react";
import { useTenant } from "@/contexts/tenant-context.tsx";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs.tsx";
import { Button } from "@/components/ui/button.tsx";
import { Badge } from "@/components/ui/badge.tsx";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card.tsx";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog.tsx";
import { Input } from "@/components/ui/input.tsx";
import { Label } from "@/components/ui/label.tsx";
import { Textarea } from "@/components/ui/textarea.tsx";
import { Switch } from "@/components/ui/switch.tsx";
import { Skeleton } from "@/components/ui/skeleton.tsx";
import { SignInButton } from "@/components/ui/signin.tsx";
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription, EmptyContent } from "@/components/ui/empty.tsx";
import { toast } from "sonner";
import {
  FileText, Plus, Trash2, Download, Eye, RefreshCw, Layers, Edit,
  CheckCircle, Clock, Package, Sparkles, ToggleLeft, ToggleRight
} from "lucide-react";
import type { Id } from "@/convex/_generated/dataModel.d.ts";

// ── Default GC document template blocks ──────────────────────────────────────

const GC_STARTER_BLOCKS = [
  { type: "header", text: "{{form_name}}", level: 1 },
  { type: "paragraph", text: "Reference Number: {{reference_number}}\nSubmitted: {{submitted_at}}\nTenant: {{tenant_name}}" },
  { type: "divider" },
  { type: "header", text: "Submission Details", level: 2 },
  { type: "all_fields" },
  { type: "divider" },
  { type: "header", text: "Declaration", level: 2 },
  { type: "paragraph", text: "This document is an official record generated by CanFlow.ai on behalf of {{tenant_name}}. The information contained herein reflects the submission data at the time of generation." },
];

const GC_CONFIRMATION_BLOCKS = [
  { type: "header", text: "Confirmation of Receipt", level: 1 },
  { type: "paragraph", text: "This confirms that we have received your submission with reference number {{reference_number}}." },
  { type: "divider" },
  { type: "header", text: "Submission Summary", level: 2 },
  { type: "all_fields" },
  { type: "spacer", height: 10 },
  { type: "paragraph", text: "Please retain this document for your records. Your submission is currently under review. You may be contacted for additional information." },
];

const GC_DECISION_BLOCKS = [
  { type: "header", text: "Decision Notice", level: 1 },
  { type: "paragraph", text: "Reference: {{reference_number}} | Date: {{generated_at}}" },
  { type: "divider" },
  { type: "header", text: "Applicant Information", level: 2 },
  { type: "all_fields" },
  { type: "divider" },
  { type: "header", text: "Decision", level: 2 },
  { type: "paragraph", text: "[Decision text to be added by reviewing officer]" },
  { type: "spacer", height: 15 },
  { type: "paragraph", text: "Authorized by: ___________________________\nDate: ___________________________\nTitle: ___________________________" },
];

type DocTemplate = {
  _id: Id<"docTemplates">;
  name: string;
  description?: string;
  format: "pdf" | "docx";
  content: string;
  mergeFields: string;
  linkedFormIds: Id<"forms">[];
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

type GeneratedDoc = {
  _id: Id<"generatedDocuments">;
  submissionId: Id<"submissions">;
  templateId: Id<"docTemplates">;
  templateName: string;
  referenceNumber: string;
  filename: string;
  format: string;
  version: string;
  generatedAt: string;
};

// ── Template Editor Dialog ────────────────────────────────────────────────────

function TemplateEditorDialog({
  tenantId,
  initial,
  onClose,
}: {
  tenantId: Id<"tenants">;
  initial?: DocTemplate | null;
  onClose: () => void;
}) {
  const createTemplate = useMutation(api.documentGeneration.createTemplate);
  const updateTemplate = useMutation(api.documentGeneration.updateTemplate);

  const [name, setName] = useState(initial?.name ?? "");
  const [description, setDescription] = useState(initial?.description ?? "");
  const [content, setContent] = useState(initial?.content ?? JSON.stringify(GC_STARTER_BLOCKS, null, 2));
  const [saving, setSaving] = useState(false);
  const [activePreset, setActivePreset] = useState<string | null>(null);

  const presets = [
    { id: "starter", label: "Full Submission Report", blocks: GC_STARTER_BLOCKS },
    { id: "confirmation", label: "Confirmation of Receipt", blocks: GC_CONFIRMATION_BLOCKS },
    { id: "decision", label: "Decision Notice", blocks: GC_DECISION_BLOCKS },
  ];

  const applyPreset = (blocks: unknown[], presetName: string) => {
    setContent(JSON.stringify(blocks, null, 2));
    if (!name) setName(presetName);
    setActivePreset(presetName);
  };

  const handleSave = async () => {
    if (!name.trim()) { toast.error("Template name is required"); return; }
    // Validate JSON
    try { JSON.parse(content); } catch { toast.error("Template content is not valid JSON"); return; }

    setSaving(true);
    try {
      if (initial) {
        await updateTemplate({ templateId: initial._id, name, description: description || undefined, content });
        toast.success("Template updated");
      } else {
        await createTemplate({
          tenantId,
          name,
          description: description || undefined,
          format: "pdf",
          content,
          mergeFields: "[]",
          linkedFormIds: [],
        });
        toast.success("Template created");
      }
      onClose();
    } catch {
      toast.error("Failed to save template");
    } finally {
      setSaving(false);
    }
  };

  return (
    <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
      <DialogHeader>
        <DialogTitle>{initial ? "Edit Template" : "New Document Template"}</DialogTitle>
      </DialogHeader>
      <div className="space-y-4 py-2">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label>Template Name *</Label>
            <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Submission Report" />
          </div>
          <div className="space-y-2">
            <Label>Description</Label>
            <Input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Optional description" />
          </div>
        </div>

        {!initial && (
          <div className="space-y-2">
            <Label>Start from a preset</Label>
            <div className="flex flex-wrap gap-2">
              {presets.map((p) => (
                <Button
                  key={p.id}
                  variant={activePreset === p.label ? "default" : "outline"}
                  size="sm"
                  onClick={() => applyPreset(p.blocks, p.label)}
                >
                  <Sparkles className="h-3 w-3 mr-1" />
                  {p.label}
                </Button>
              ))}
            </div>
          </div>
        )}

        <div className="space-y-2">
          <Label className="flex items-center gap-2">
            Template Content (JSON)
            <Badge variant="secondary" className="text-xs font-mono">JSON array of blocks</Badge>
          </Label>
          <p className="text-xs text-muted-foreground">
            Supported block types: <code>header</code>, <code>paragraph</code>, <code>field_value</code>, <code>table</code>, <code>all_fields</code>, <code>divider</code>, <code>spacer</code>.
            Use <code>{"{{reference_number}}"}</code>, <code>{"{{form_name}}"}</code>, <code>{"{{tenant_name}}"}</code>, <code>{"{{submitted_at}}"}</code> as merge tags.
          </p>
          <Textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            rows={16}
            className="font-mono text-xs"
            placeholder="[]"
          />
        </div>
      </div>
      <DialogFooter>
        <Button variant="ghost" onClick={onClose}>Cancel</Button>
        <Button onClick={handleSave} disabled={saving}>
          {saving ? <RefreshCw className="h-4 w-4 mr-2 animate-spin" /> : <CheckCircle className="h-4 w-4 mr-2" />}
          {initial ? "Save Changes" : "Create Template"}
        </Button>
      </DialogFooter>
    </DialogContent>
  );
}

// ── Templates Tab ─────────────────────────────────────────────────────────────

function TemplatesTab({ tenantId }: { tenantId: Id<"tenants"> }) {
  const templates = useQuery(api.documentGeneration.listTemplates, { tenantId }) as DocTemplate[] | undefined;
  const updateTemplate = useMutation(api.documentGeneration.updateTemplate);
  const deleteTemplate = useMutation(api.documentGeneration.deleteTemplate);

  const [showCreate, setShowCreate] = useState(false);
  const [editTarget, setEditTarget] = useState<DocTemplate | null>(null);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold">Document Templates</h2>
          <p className="text-sm text-muted-foreground">Define reusable PDF templates populated from form submission data</p>
        </div>
        <Button onClick={() => setShowCreate(true)}>
          <Plus className="h-4 w-4 mr-2" /> New Template
        </Button>
      </div>

      {templates === undefined ? (
        <div className="space-y-3">{Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-20 w-full" />)}</div>
      ) : templates.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyMedia variant="icon"><FileText /></EmptyMedia>
            <EmptyTitle>No templates yet</EmptyTitle>
            <EmptyDescription>Create your first document template to generate PDFs from form submissions</EmptyDescription>
          </EmptyHeader>
          <EmptyContent>
            <Button size="sm" onClick={() => setShowCreate(true)}><Plus className="h-4 w-4 mr-2" />New Template</Button>
          </EmptyContent>
        </Empty>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {templates.map((t) => (
            <Card key={t._id} className={t.isActive ? "" : "opacity-60"}>
              <CardHeader className="pb-2">
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <CardTitle className="text-base">{t.name}</CardTitle>
                    {t.description && <CardDescription className="mt-1">{t.description}</CardDescription>}
                  </div>
                  <div className="flex items-center gap-1">
                    <Badge variant={t.format === "pdf" ? "default" : "secondary"} className="text-xs uppercase">{t.format}</Badge>
                    <Badge variant={t.isActive ? "default" : "outline"} className="text-xs">
                      {t.isActive ? "Active" : "Inactive"}
                    </Badge>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                <p className="text-xs text-muted-foreground mb-3">
                  Updated {new Date(t.updatedAt).toLocaleDateString("en-CA")}
                </p>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={() => setEditTarget(t)}>
                    <Edit className="h-3 w-3 mr-1" /> Edit
                  </Button>
                  <Button
                    variant="outline" size="sm"
                    onClick={() => updateTemplate({ templateId: t._id, isActive: !t.isActive })
                      .then(() => toast.success(t.isActive ? "Template disabled" : "Template enabled"))}
                  >
                    {t.isActive ? <ToggleRight className="h-3 w-3 mr-1" /> : <ToggleLeft className="h-3 w-3 mr-1" />}
                    {t.isActive ? "Disable" : "Enable"}
                  </Button>
                  <Button
                    variant="ghost" size="sm"
                    onClick={() => deleteTemplate({ templateId: t._id })
                      .then(() => toast.success("Template deleted"))
                      .catch(() => toast.error("Failed to delete"))}
                  >
                    <Trash2 className="h-3 w-3 text-destructive" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Dialog open={showCreate} onOpenChange={setShowCreate}>
        {showCreate && (
          <TemplateEditorDialog
            tenantId={tenantId}
            onClose={() => setShowCreate(false)}
          />
        )}
      </Dialog>

      <Dialog open={!!editTarget} onOpenChange={(o) => !o && setEditTarget(null)}>
        {editTarget && (
          <TemplateEditorDialog
            tenantId={tenantId}
            initial={editTarget}
            onClose={() => setEditTarget(null)}
          />
        )}
      </Dialog>
    </div>
  );
}

// ── Generate Panel — select submission + template and generate ────────────────

function GenerateTab({ tenantId }: { tenantId: Id<"tenants"> }) {
  const templates = useQuery(api.documentGeneration.listTemplates, { tenantId }) as DocTemplate[] | undefined;
  const generatePdf = useAction(api.documentGenerationAction.generatePdfForSubmission);

  const [submissionId, setSubmissionId] = useState("");
  const [templateId, setTemplateId] = useState<Id<"docTemplates"> | "">("");
  const [generating, setGenerating] = useState(false);
  const [lastResult, setLastResult] = useState<{ dataUri: string; filename: string } | null>(null);

  const activeTemplates = templates?.filter((t) => t.isActive) ?? [];

  const handleGenerate = async () => {
    if (!submissionId.trim() || !templateId) {
      toast.error("Enter a submission ID and select a template");
      return;
    }
    setGenerating(true);
    setLastResult(null);
    try {
      const result = await generatePdf({
        submissionId: submissionId.trim() as Id<"submissions">,
        templateId: templateId as Id<"docTemplates">,
      });
      setLastResult(result);
      toast.success("PDF generated successfully");
    } catch (e) {
      toast.error(String(e));
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!lastResult) return;
    const a = document.createElement("a");
    a.href = lastResult.dataUri;
    a.download = lastResult.filename;
    a.click();
  };

  const handlePreview = () => {
    if (!lastResult?.dataUri) return;
    window.open(lastResult.dataUri, "_blank");
  };

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h2 className="text-lg font-semibold">Generate a Document</h2>
        <p className="text-sm text-muted-foreground">Select a submission and template to produce a PDF on-demand</p>
      </div>

      <Card>
        <CardContent className="py-6 space-y-4">
          <div className="space-y-2">
            <Label>Submission ID</Label>
            <Input
              value={submissionId}
              onChange={(e) => setSubmissionId(e.target.value)}
              placeholder="Paste the submission _id here"
              className="font-mono text-sm"
            />
            <p className="text-xs text-muted-foreground">
              Find the submission ID in the Task Queue or Submissions page
            </p>
          </div>

          <div className="space-y-2">
            <Label>Document Template</Label>
            {activeTemplates.length === 0 ? (
              <p className="text-sm text-muted-foreground">No active templates. Create one in the Templates tab first.</p>
            ) : (
              <div className="grid gap-2">
                {activeTemplates.map((t) => (
                  <button
                    key={t._id}
                    onClick={() => setTemplateId(t._id)}
                    className={`flex items-center gap-3 p-3 rounded-lg border text-left transition-colors cursor-pointer ${templateId === t._id ? "border-primary bg-accent" : "hover:bg-accent/50"}`}
                  >
                    <FileText className="h-5 w-5 text-muted-foreground shrink-0" />
                    <div>
                      <p className="text-sm font-medium">{t.name}</p>
                      {t.description && <p className="text-xs text-muted-foreground">{t.description}</p>}
                    </div>
                    <Badge variant="secondary" className="ml-auto text-xs uppercase">{t.format}</Badge>
                  </button>
                ))}
              </div>
            )}
          </div>

          <Button
            className="w-full"
            onClick={handleGenerate}
            disabled={generating || !submissionId.trim() || !templateId}
          >
            {generating ? (
              <><RefreshCw className="h-4 w-4 mr-2 animate-spin" />Generating PDF...</>
            ) : (
              <><Sparkles className="h-4 w-4 mr-2" />Generate PDF</>
            )}
          </Button>
        </CardContent>
      </Card>

      {lastResult && (
        <Card className="border-green-200 bg-green-50 dark:bg-green-950/20 dark:border-green-900">
          <CardContent className="py-4 flex items-center gap-4">
            <CheckCircle className="h-6 w-6 text-green-600 shrink-0" />
            <div className="flex-1 min-w-0">
              <p className="font-medium text-green-800 dark:text-green-300">PDF ready</p>
              <p className="text-sm text-green-700 dark:text-green-400 truncate">{lastResult.filename}</p>
            </div>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={handlePreview}>
                <Eye className="h-4 w-4 mr-1" /> Preview
              </Button>
              <Button size="sm" onClick={handleDownload}>
                <Download className="h-4 w-4 mr-1" /> Download
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

// ── Document History Tab ──────────────────────────────────────────────────────

function HistoryTab({ tenantId }: { tenantId: Id<"tenants"> }) {
  const docs = useQuery(api.documentGeneration.listGeneratedDocsByTenant, { tenantId }) as GeneratedDoc[] | undefined;

  if (docs === undefined) {
    return <div className="space-y-3">{Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-14 w-full" />)}</div>;
  }

  if (docs.length === 0) {
    return (
      <Empty>
        <EmptyHeader>
          <EmptyMedia variant="icon"><Layers /></EmptyMedia>
          <EmptyTitle>No documents generated yet</EmptyTitle>
          <EmptyDescription>Generated PDFs will appear here with full version history</EmptyDescription>
        </EmptyHeader>
      </Empty>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold">Generated Documents</h2>
        <Badge variant="secondary">{docs.length} document{docs.length !== 1 ? "s" : ""}</Badge>
      </div>
      <div className="space-y-2">
        {docs.map((doc) => (
          <Card key={doc._id}>
            <CardContent className="py-3 flex items-center gap-3">
              <div className="p-2 bg-red-50 dark:bg-red-950/30 rounded-md shrink-0">
                <FileText className="h-4 w-4 text-red-600" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <p className="text-sm font-medium truncate">{doc.filename}</p>
                  <Badge variant="outline" className="text-xs shrink-0">{doc.version}</Badge>
                </div>
                <div className="flex items-center gap-3 mt-0.5">
                  <span className="text-xs text-muted-foreground">{doc.templateName}</span>
                  <span className="text-xs text-muted-foreground">•</span>
                  <span className="text-xs text-muted-foreground">{doc.referenceNumber}</span>
                  <span className="text-xs text-muted-foreground">•</span>
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    {new Date(doc.generatedAt).toLocaleString("en-CA", { dateStyle: "medium", timeStyle: "short" })}
                  </span>
                </div>
              </div>
              <Badge variant="secondary" className="text-xs uppercase shrink-0">{doc.format}</Badge>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

function DocumentsInner() {
  const { activeTenant } = useTenant();

  if (!activeTenant) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-4 text-center p-6">
        <Package className="h-10 w-10 text-muted-foreground" />
        <p className="text-muted-foreground">Select a tenant to manage document templates</p>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Document Generation</h1>
        <p className="text-muted-foreground">Create PDF templates, generate documents from submissions, and manage document history</p>
      </div>

      <Tabs defaultValue="templates">
        <TabsList>
          <TabsTrigger value="templates" className="flex items-center gap-2">
            <FileText className="h-4 w-4" /> Templates
          </TabsTrigger>
          <TabsTrigger value="generate" className="flex items-center gap-2">
            <Sparkles className="h-4 w-4" /> Generate
          </TabsTrigger>
          <TabsTrigger value="history" className="flex items-center gap-2">
            <Layers className="h-4 w-4" /> History
          </TabsTrigger>
        </TabsList>
        <TabsContent value="templates" className="mt-6">
          <TemplatesTab tenantId={activeTenant._id} />
        </TabsContent>
        <TabsContent value="generate" className="mt-6">
          <GenerateTab tenantId={activeTenant._id} />
        </TabsContent>
        <TabsContent value="history" className="mt-6">
          <HistoryTab tenantId={activeTenant._id} />
        </TabsContent>
      </Tabs>
    </div>
  );
}

export default function DocumentsPage() {
  return (
    <>
      <Unauthenticated>
        <div className="flex items-center justify-center h-full">
          <SignInButton />
        </div>
      </Unauthenticated>
      <Authenticated>
        <DocumentsInner />
      </Authenticated>
    </>
  );
}
